package com.polarj.workflow.model;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.polarj.model.GenericDbInfo;
import com.polarj.model.annotation.FieldMetaData;
import com.polarj.model.annotation.ModelMetaData;

import lombok.Getter;
import lombok.Setter;

// 工作流的描述
// code+version唯一， 使用工作流时，一定要有版本号
@ModelMetaData(showDetailFieldName = "code", deletable = false, batchDeletable = false, addible = false,
        uploadable = false)
@Entity
@Table(name = "workflow")
public class WorkflowSpec extends GenericDbInfo
{
    private static final long serialVersionUID = 7871816734849557530L;

    // 工作流代码/名称
    @FieldMetaData(position=10, label="Code", autogenerated=true)
    @Column(length = 64)
    private @Getter @Setter String code;

    // 工作流版本
    // 新建的工作流实例要用最新的版本
    @FieldMetaData(position=20, dataType="number", label="Version", autogenerated=true)
    @Column
    private @Getter @Setter Integer version;

    // 工作流描述，需要国际化
    @FieldMetaData(position=30, label="Description", maxLength=1000, hide=true)
    @Column(length = 1024)
    private @Getter @Setter String description;

    // 上一级状态图中的步骤代码
    @FieldMetaData(position=40, label="Parent Step Code", maxLength=60, hide=true)
    @Column(length = 64)
    private @Getter @Setter String parentStepCode;

    // 这个工作流的所有步骤
    @FieldMetaData(position = 50, label = "Steps", dataType = "array")
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
    @JoinColumn(name = "workflowSpecId", nullable = false,
            foreignKey = @ForeignKey(name = "FK_WorkflowSpec_WorkflowStep_Id"))
    private @Getter @Setter List<WorkflowStep> steps;
}
