package com.dragoncargo.sales.model;

import com.dragoncargo.customer.model.CustomerCenter;
import com.dragoncargo.customer.model.SpecialQuotation;
import com.dragoncargo.general.model.Airline;
import com.dragoncargo.general.model.AirportWarehouse;
import com.dragoncargo.general.model.AviationCompany;
import com.dragoncargo.omm.model.FlightInfo;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.polarj.model.GenericDbInfo;
import com.polarj.model.HasOwner;
import com.polarj.model.UserAccount;
import com.polarj.model.annotation.FieldMetaData;
import com.polarj.model.annotation.ModelMetaData;
import com.polarj.model.enumeration.FieldMetaDataSupportedDataType;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * 询价方案
 */
@ModelMetaData(label = "QuoteCharge",showDetailFieldName = "quoteScheme")
@Entity
@Table(name = "quotescheme")
public class QuoteScheme extends GenericDbInfo implements HasOwner {

    /**
     *  序列号生产器生产的系统方案编号
     */
    @FieldMetaData(position = 10, label = "Scheme Num", autogenerated = true)
    @Column(length = 64)
    private @Getter @Setter String schemeNum;

    /**
     * 查询条件
     */
    @FieldMetaData(position = 20, label = "QueryCondition", dataType = FieldMetaDataSupportedDataType.OBJECT,
            labelField = "origin")
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
    @JoinColumn(name = "queryConditionId", foreignKey = @ForeignKey(name = "FK_Query_Condition_Id"), referencedColumnName = "id",nullable = true)
    private @Setter @Getter QueryCondition queryCondition;

    /**
     * 航司
     */
    @FieldMetaData(position = 30, label = "Aviation Company", dataType = FieldMetaDataSupportedDataType.OBJECT,
            enumClass = AviationCompany.class, labelField = "code")
    @ManyToOne
    @JoinColumn(name = "aviationcompanyId",
            foreignKey = @ForeignKey(name = "fk_quotescheme_aviationcompanyid"),
            referencedColumnName = "id")
    private @Setter @Getter AviationCompany aviationCompany;

    /**
     * 航线
     */
    @FieldMetaData(position = 40, label = "Airline", dataType = FieldMetaDataSupportedDataType.OBJECT,
            enumClass = Airline.class, labelField = "code")
    @ManyToOne
    @JoinColumn(name = "airlineId", foreignKey = @ForeignKey(name = "fk_quotescheme_airlineId"),
            referencedColumnName = "id")
    private @Setter @Getter Airline airline;

    /**
     *
     * 国际货站 International Cargo Centre Shenzhen（ICCS） 物流园 Logistics Park
     *
     */
    @FieldMetaData(position = 50, label = "Airport Warehouse", dataType = FieldMetaDataSupportedDataType.OBJECT,
            enumClass = AirportWarehouse.class, labelField = "name")
    @ManyToOne
    @JoinColumn(name = "airportWarehouseId",
            foreignKey = @ForeignKey(name = "fk_quotescheme_airportwarehouseid"),
            referencedColumnName = "id")
    private @Setter @Getter AirportWarehouse airportWarehouse;

    /**
     * 航班(包板是可以确定航班的)
     */
    @FieldMetaData(position = 60, label = "Flight Info Item", dataType = FieldMetaDataSupportedDataType.ARRAY,
            labelField = "flightCode", enumClass = FlightInfo.class, multiChoice = true,autogenerated = true)
    @ManyToMany
    @JoinTable(name = "quotescheme_flightinfo",
            joinColumns = @JoinColumn(name = "bookingOrderId",
                    foreignKey = @ForeignKey(name = "fk_quotescheme_flightinfo_bookingOrderId")),
            inverseJoinColumns = @JoinColumn(name = "forecastFlightId",
                    foreignKey = @ForeignKey(name = "fk_quotescheme_flightinfo_forecastFlightId")))
    private @Setter @Getter List<FlightInfo> flightList;


    /**
     * 费用 所有费有
     */
    @FieldMetaData(position = 70, label = "QuoteCharge Item", labelField = "chargeRateItem",
            dataType = FieldMetaDataSupportedDataType.ARRAY)
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "quoteSchemeId", foreignKey = @ForeignKey(name = "FK_Quote_Charge_Item_Id"))
    private @Setter @Getter List<QuoteChargeItem> quoteChargeItem;

    /**
     * 特殊报价项
     */
    @FieldMetaData(position = 75, label = "QuoteSpecialFee", dataType = FieldMetaDataSupportedDataType.ARRAY,
            labelField = "name",autogenerated = true)
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "quoteSchemeId", foreignKey = @ForeignKey(name = "FK_QuoteScheme_QuoteSpecialFee_Id"))
    private @Getter @Setter List<QuoteSpecialFee> quoteSpecialFees;

    /**
     * 服务时效
     */
    @FieldMetaData(position = 80, label = "Prescription")
    @Column(length = 64)
    private @Setter @Getter String prescription;


    /**
     * 客户档案
     */
    @FieldMetaData(position = 90, label = "Customer Center", dataType = FieldMetaDataSupportedDataType.OBJECT,
            labelField = "customerCode",enumClass = CustomerCenter.class)
    @ManyToOne
    @JoinColumn(name = "customerCenterId", foreignKey = @ForeignKey(name = "fk_quoteScheme_customerCenter_id"), referencedColumnName = "id")
    private @Getter @Setter CustomerCenter customerCenter;

    /**
     * 分泡比率 50%= 0.5 60%=0.6,默认不分泡则为0
     */
    @FieldMetaData(position = 100, label = "Bubble Rate", dataType = FieldMetaDataSupportedDataType.NUMBER)
    @Column
    private @Setter @Getter Double bubbleRate;

    /**
     * 失效日期
     */
    @FieldMetaData(position = 110, label = "Expired Date", dataType = FieldMetaDataSupportedDataType.DATE,
            formatter = FieldMetaDataSupportedDataType.DATEFORMAT)
    @Column(length = 32)
    private @Setter @Getter Date expiredDate;

    /**
     * owner
     */
    @FieldMetaData(position = 120, label = "Owner", dataType = FieldMetaDataSupportedDataType.OBJECT, labelField = "loginName",
            managementSeparately = true, autogenerated = true, hasDetail = false)
    @ManyToOne
    @JoinColumn(name = "ownerId", foreignKey = @ForeignKey(name = "fk_quoteScheme_useraccount_ownerid"), referencedColumnName = "id")
    private @Getter @Setter UserAccount owner;

    /**
     * 注意事项
     */
    @FieldMetaData(position = 130, label = "Memo")
    @Column(length = 200)
    private @Setter @Getter String memo;

}
