package com.dragoncargo.sales.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

import com.dragoncargo.general.model.*;
import com.dragoncargo.omm.model.ChargeRateItem;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.polarj.model.GenericDbInfo;
import com.polarj.model.annotation.FieldMetaData;
import com.polarj.model.annotation.ModelMetaData;
import com.polarj.model.enumeration.FieldMetaDataSupportedDataType;

import lombok.Getter;
import lombok.Setter;


/**
 * 询价费用项明细
 */
@ModelMetaData(label = "QuoteChargeItem",showDetailFieldName = "quoteChargeItem")
@Entity
@Table(name = "quotechargeitem")
//@Inheritance(strategy = InheritanceType.JOINED)
//@DiscriminatorColumn(name = "classification")
public class QuoteChargeItem extends GenericDbInfo {

    /**
     * 区域code 比如深圳 广州
     */
    @FieldMetaData(position = 10, label = "AreaCode",autogenerated = true,hide = true)
    @Column(length = 100)
    private @Setter @Getter String areaCode;

//    /**
//     * 报价项目编码
//     */
//    @FieldMetaData(position = 20, label = "ChargeRateCode")
//    @Column(length = 100)
//    private @Setter @Getter String chargeRateCode;


    /**
     * 报价项目
     */
    @FieldMetaData(position = 20, label = "Charge Rate Item", dataType = FieldMetaDataSupportedDataType.OBJECT,
            enumClass = ChargeRateItem.class, labelField = "name")
    @ManyToOne
    @JoinColumn(name = "chargeRateItemId",
            foreignKey = @ForeignKey(name = "fk_quoteChargeItem_chargerateitemid"),
            referencedColumnName = "id")
    private @Setter @Getter ChargeRateItem chargeRateItem;

//    /**
//     * 计费单位, 重量 票 操作次数 个 页 天
//     */
//    @FieldMetaData(position = 25, label = "ChargeUnit")
//    @Column(length = 100)
//    private @Setter @Getter String chargeUnit;

    /**
     * 计费单位, 重量(毛重，计费重) 票 操作次数 个 页 天
     */
    @FieldMetaData(position = 25, label = "Charge Unit", dataType = FieldMetaDataSupportedDataType.OBJECT,
            enumClass = ChargeUnit.class, labelField = "name")
    @ManyToOne
    @JoinColumn(name = "chargeUnitId", foreignKey = @ForeignKey(name = "fk_quoteChargeItem_chargeUnitid"),
            referencedColumnName = "id")
    private @Setter @Getter ChargeUnit chargeUnit;


    /**
     * 公开报价
     */
    @FieldMetaData(position = 30, label = "UnitPriceInfo", dataType = FieldMetaDataSupportedDataType.OBJECT,
        labelField = "unitPrice",embedded = true,formatter = "${unitPrice}")
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "unitPriceInfoId", foreignKey = @ForeignKey(name = "FK_QuoteChargeItem_unitPriceInfo_Id"))
    private @Getter @Setter QuotePriceInfo unitPriceInfo;

    /**
     * 最低销售价
     */
    @FieldMetaData(position = 40, label = "MinSalesPriceInfo", dataType = FieldMetaDataSupportedDataType.OBJECT,
            labelField = "unitPrice",embedded = true,formatter = "${unitPrice}",autogenerated = true)
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "minSalesPriceInfoId", foreignKey = @ForeignKey(name = "FK_QuoteChargeItem_minSalesPriceInfo_Id"))
    private @Getter @Setter QuotePriceInfo minSalesPriceInfo;

    /**
     * 销售成本价格
     */
    @FieldMetaData(position = 40, label = "SalesCostPriceInfo", dataType = FieldMetaDataSupportedDataType.OBJECT,
            labelField = "unitPrice",embedded = true,formatter = "${unitPrice}",autogenerated = true,detailHide = true)
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "salesCostPriceInfoId", foreignKey = @ForeignKey(name = "FK_QuoteChargeItem_salesCostPriceInfo_Id"))
    private @Getter @Setter QuotePriceInfo salesCostPriceInfo;

    /**
     * 公司成本价格
     */
    @FieldMetaData(position = 40, label = "CompanyCostPriceInfo", dataType = FieldMetaDataSupportedDataType.OBJECT,
            labelField = "unitPrice",embedded = true,formatter = "${unitPrice}",autogenerated = true,detailHide = true)
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "companyCostPriceInfoId", foreignKey = @ForeignKey(name = "FK_QuoteChargeItem_companyCostPriceInfo_Id"))
    private @Getter @Setter QuotePriceInfo companyCostPriceInfo;

    /**
     * 最低收费
     */
    @FieldMetaData(position = 50, label = "Minimum Charge", dataType = FieldMetaDataSupportedDataType.OBJECT,
            embedded = true, formatter = "${currency}${amount}",autogenerated = true,hide = true)
    @Embedded
    @AttributeOverrides({ @AttributeOverride(name = "currency", column = @Column(name = "minimumChargeCurrency")),
            @AttributeOverride(name = "amount", column = @Column(name = "minimumChargeValue")) })
    private @Setter @Getter FeeInfo minimumCharge;

    /**
     * 最高收费
     */
    @FieldMetaData(position = 60, label = "Maximum Charge", dataType = FieldMetaDataSupportedDataType.OBJECT,
            embedded = true, formatter = "${currency}${amount}",autogenerated = true,hide = true)
    @Embedded
    @AttributeOverrides({ @AttributeOverride(name = "currency", column = @Column(name = "maximumChargeCurrency")),
            @AttributeOverride(name = "amount", column = @Column(name = "maximumChargeValue")) })
    private @Setter @Getter FeeInfo maximumCharge;

    /**
     * 生效日期
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm")
    @FieldMetaData(position = 70, label = "Effective Date", dataType = FieldMetaDataSupportedDataType.DATE,
            formatter = "yyyy-MM-dd hh:mm",autogenerated = true,hide = true,detailHide = true)
    @Column(length = 32)
    private @Setter @Getter Date effetiveDate;

    /**
     * 失效日期
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm")
    @FieldMetaData(position = 80, label = "Expired Date", dataType = FieldMetaDataSupportedDataType.DATE,
            formatter = "yyyy-MM-dd hh:mm",autogenerated = true,hide = true,detailHide = true)
    @Column(length = 32)
    private @Setter @Getter Date expiredDate;



    /**
     * 费用类型 FreightRate,AviationCompanyLocalChargeRate,AirportWarehouseLocalChargeRate,AirportLocalChargeRate
     */
//    @FieldMetaData(position = 90, label = "Charge Type", dataType = FieldMetaDataSupportedDataType.OBJECT,
//            enumClass = ChargeItemType.class, labelField = "name")
//    @ManyToOne
//    @JoinColumn(name = "chargeItemTypeId", foreignKey = @ForeignKey(name = "fk_quoteChargeItem_chargeItemTypeId"),
//            referencedColumnName = "id")
//    private @Setter @Getter ChargeItemType chargeItemType;

    /**
     * 判断是否运费,运费关联id不为空
     */
//    @FieldMetaData(position = 40, label = "QuoteFreightFee", dataType = FieldMetaDataSupportedDataType.OBJECT,
//            labelField = "name")
    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "quoteFreightFeeId", foreignKey = @ForeignKey(name = "FK_QuoteChargeItem_QuoteFreightFee_Id"))
    private @Getter @Setter QuoteFreightFee quoteFreightFee;

    /**
     * 是否一定产生
     */
    @FieldMetaData(position = 100, label = "Estimate Available", dataType = FieldMetaDataSupportedDataType.BOOLEAN)
    @Column
    private @Setter @Getter Boolean estimateAvailable;

    /**
     * 备注
     */
    @FieldMetaData(position = 200, label = "Memo")
    @Column(length = 2048)
    private @Setter @Getter String Memo;

    /**
     * 费用总额
     */
    @Transient
    private @Setter @Getter String totalCurrency;

    @Transient
    private @Setter @Getter BigDecimal total;
}
