package com.polarj.workflow.model;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;

import com.polarj.model.GenericDbInfo;
import com.polarj.model.annotation.FieldMetaData;

import lombok.Getter;
import lombok.Setter;

@MappedSuperclass
public abstract class ModelWithWorkflowStep extends GenericDbInfo
{
    private static final long serialVersionUID = 6064775357694253953L;

    // QUES: 工作流如何处理比较好？目前暂时在参与工作流的业务模型中增加工作流步骤描述来做。
    // 描述当前处于工作流的那个步骤上，不需要传到客户端
    // 对应工作流步骤在数据库中的内容，同时，其子类可以有状态与其对应
    // 创建状态与工作流步骤的对应表
    @FieldMetaData(autogenerated = true, label = "Workflow Step", position = 9999, hide = true)
    @Column(length = 128)
    private @Getter @Setter String workflowStep;
    
    //工作流实例ID，方便定单查找工作流相关数据
    @FieldMetaData(autogenerated = true, label = "Workflow instance id", position = 9999, hide = true)
    @Column(length = 128)
    private @Getter @Setter String wfPid;

}
