package com.dragoncargo.general.model;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.polarj.model.GenericDbInfo;
import com.polarj.model.HasOwner;
import com.polarj.model.UserAccount;
import com.polarj.model.annotation.FieldMetaData;
import com.polarj.model.annotation.ModelMetaData;
import com.polarj.model.enumeration.FieldMetaDataSupportedDataType;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

//货品信息管理
@ModelMetaData(label = "GoodsInfo", showDetailFieldName = "goodsCode")
@Entity
@Table(name = "goodsinfo")
public @ToString @EqualsAndHashCode(callSuper = false) class GoodsInfo extends GenericDbInfo implements HasOwner {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@FieldMetaData(position = 10, label = "GoodsCode Code", dataType = FieldMetaDataSupportedDataType.STRING, labelField = "code")
	@Column
	private @Getter @Setter String goodsCode;

	// 航空公司代码'
	@FieldMetaData(position = 20, label = "AviationCompanyCode Code", dataType = FieldMetaDataSupportedDataType.STRING, labelField = "code")
	@Column
	private @Getter @Setter String aviationCompanyCode;

	// 适用国内
    @FieldMetaData(position = 30, label = "Suit Domestic", dataType = FieldMetaDataSupportedDataType.BOOLEAN)
    @Column
	private @Getter @Setter Boolean suitDomestic;

	// 适用国际
    @FieldMetaData(position = 40, label = "Suit International", dataType = FieldMetaDataSupportedDataType.BOOLEAN)
    @Column
	private @Getter @Setter Boolean suitInternational;
	
	
	@FieldMetaData(position = 50, label = "Owner", dataType = FieldMetaDataSupportedDataType.OBJECT, labelField = "loginName", managementSeparately = true, autogenerated = true, hasDetail = false)
	@ManyToOne
	@JoinColumn(name = "ownerId", foreignKey = @ForeignKey(name = "fk_goodsinfo_useraccount_ownerid"), referencedColumnName = "id")
	private @Getter @Setter UserAccount owner;

}
