#debug: on
#trace: on
spring:
  application:
    name: youjiabackend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
hibernate:
  packagesToScan: 
    - com.polarj.model
    - com.dragoncargo.omm.model
    - com.dragoncargo.general.model
    - com.dragoncargo.customer.model
    - com.dragoncargo.sales.model
    - com.hwcargo.model
    - com.youjia.model
  repositoriesToScan: 
    - com.polarj.model.repository
    - com.dragoncargo.omm.model.repository
    - com.dragoncargo.general.model.repository
    - com.dragoncargo.customer.model.repository
    - com.dragoncargo.sales.model.repository
    - com.hwcargo.model.repository
    - com.youjia.model.repository
server:
  servlet:
    context-path: /${spring.application.name}
workflow:
  enable: false
scheduler:
  enable: true